###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email":"xiaoming@ning.com",
    "pass":"xiaoming"
}


###
GET http://localhost:3000/getInfo
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjozLCJlbWFpbCI6InhpYW9taW5nQG5pbmcuY29tIiwicGFzcyI6IiQyYiQxMCRhbjBXWmNIOTRYdTRkVDNLQ2pBLmR1a20xVjQxNGxJd1lEMU13LlVaUGdOaUZjNnRsVmxKZSIsIm5hbWUiOiJ4aWFvbWluZyJ9LCJpYXQiOjE3MDQ4Nzk1MjAsImV4cCI6MTcwNDg5MDMyMH0.FtVP3DMLy_cztcCQ6E2Mcgxn16wMDHeELLDk_4TnQqU