@host = http://localhost:3000


### register
POST {{host}}/signup
Content-Type: application/json

{
    "name":"xiaoming",
    "pass":"xiaoming",
    "email":"xiaoming@ning.com"
}

###
GET {{host}}/users